### ISSUE TITLE
Issue with extendmatrix gem

### ISSUE THREAD

**Issue by lokeshh** [marcandre/backports#101]
Not sure if it's a bug or is it something that doesn't have to do with backports. Please let me know if later is the case:

This works:

``` ruby
2.2.1 :001 > require 'backports'
 => true 
2.2.1 :002 > require 'extendmatrix'
 => true 
2.2.1 :003 > a = Matrix[[1], [2], [3]]
 => Matrix[[1], [2], [3]] 
2.2.1 :004 > a[0..-1, 0]
 => Vector[1, 2, 3] 
```

but this doesn't:

``` ruby
2.2.1 :001 > require 'extendmatrix'
 => true 
2.2.1 :002 > require 'backports'
 => true 
2.2.1 :003 > a = Matrix[[2], [3], [4]]
 => Matrix[[2], [3], [4]] 
2.2.1 :004 > a[0..-1, 0]
TypeError: no implicit conversion of Range into Integer
        from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/backports-3.6.8/lib/backports/1.9.2/stdlib/matrix.rb:315:in `fetch'
        from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/backports-3.6.8/lib/backports/1.9.2/stdlib/matrix.rb:315:in `[]'
        from (irb):4
        from /home/ubuntu/.rvm/rubies/ruby-2.2.1/bin/irb:11:in `<main>'
```

**Comment by marcandre** [comment]
Probably too late to be useful, but `extendmatrix` redefines methods of `Matrix` (and doesn't do this by prepending  a module), so yeah, loading order will matter.
