### ISSUE TITLE
Test failure on guix

### ISSUE THREAD

**Issue by swedebugia** [marcandre/backports#127]
On guix we get a test failure with the gem version 3.11.4 and ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]

Any ideas?

```
sdb@antelope /tmp/guix-build-ruby-backports-3.11.4.drv-0/gem$ rake test --trace
** Invoke test (first_time)
** Execute test
/tmp/guix-build-ruby-backports-3.11.4.drv-0/gem/test/_backport_guards_test.rb:54: warning: constant ::Bignum is deprecated
/tmp/guix-build-ruby-backports-3.11.4.drv-0/gem/test/_backport_guards_test.rb:54: warning: constant ::Fixnum is deprecated
/tmp/guix-build-ruby-backports-3.11.4.drv-0/gem/test/lazy_test.rb:212: warning: assigned but unused variable - enum
/tmp/guix-build-ruby-backports-3.11.4.drv-0/gem/test/lazy_test.rb:304: warning: assigned but unused variable - bug7696
Loaded suite /gnu/store/r9icr5yga7r47jdpvzrj5lbmqsw5s9b8-ruby-2.4.3/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_test_loader
Started
.....F
=================================================================================================================================
Failure:
  <{Array=>[".alias_method_chain"],
   Binding=>[".alias_method_chain"],
   Integer=>[".alias_method_chain"],
   Dir=>[".alias_method_chain"],
   Comparable=>[".alias_method_chain"],
   Enumerable=>[".alias_method_chain"],
   FalseClass=>[".alias_method_chain"],
   Float=>[".alias_method_chain"],
   GC=>[".alias_method_chain"],
   Hash=>[".alias_method_chain"],
   IO=>[".alias_method_chain"],
   Kernel=>[".alias_method_chain"],
   Math=>[".alias_method_chain"],
   MatchData=>[".alias_method_chain"],
   Method=>[".alias_method_chain"],
   Module=>[:alias_method_chain, ".alias_method_chain"],
   NilClass=>[".alias_method_chain"],
   Numeric=>[".alias_method_chain"],
   ObjectSpace=>[".alias_method_chain"],
   Proc=>[".alias_method_chain"],
   Process=>[".alias_method_chain"],
   Range=>[".alias_method_chain"],
   Regexp=>[".alias_method_chain"],
   String=>[".alias_method_chain"],
   Struct=>[".alias_method_chain"],
   Symbol=>[".alias_method_chain"],
   TrueClass=>[".alias_method_chain"],
   #<Class:#<Object:0x0000562db3cd8f48>>=>[".alias_method_chain"],
   #<Class:#<ARGF.class:0x0000562db3cd0b18>>=>[".alias_method_chain"],
   Enumerator=>[".alias_method_chain"]}> expected to be nil.
test_rails(AAA_TestBackportGuards)
/tmp/guix-build-ruby-backports-3.11.4.drv-0/gem/test/_backport_guards_test.rb:151:in `test_rails'
     148:     before = digest
     149:     require "backports/rails"
     150:     after = digest
  => 151:     assert_nil digest_delta(before, after)
     152:   end
     153: end
=================================================================================================================================
.............................................

Finished in 1.461056937 seconds.
---------------------------------------------------------------------------------------------------------------------------------
51 tests, 170 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
98.0392% passed
---------------------------------------------------------------------------------------------------------------------------------
34.91 tests/s, 116.35 assertions/s
rake aborted!
Command failed with status (1): [ruby -w -I"lib:lib:test" -I"/gnu/store/r9icr5yga7r47jdpvzrj5lbmqsw5s9b8-ruby-2.4.3/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib" "/gnu/store/r9icr5yga7r47jdpvzrj5lbmqsw5s9b8-ruby-2.4.3/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb" "test/_backport_guards_\
test.rb" "test/bit_length_test.rb" "test/lazy_test.rb" "test/socket_interaction_test.rb" ]
/gnu/store/r9icr5yga7r47jdpvzrj5lbmqsw5s9b8-ruby-2.4.3/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/testtask.rb:128:in `block (3 levels) in define'
/gnu/store/r9icr5yga7r47jdpvzrj5lbmqsw5s9b8-ruby-2.4.3/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/file_utils.rb:56:in `sh'
/gnu/store/r9icr5yga7r47jdpvzrj5lbmqsw5s9b8-ruby-2.4.3/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/file_utils.rb:104:in `ruby'
/gnu/store/r9icr5yga7r47jdpvzrj5lbmqsw5s9b8-ruby-2.4.3/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/testtask.rb:115:in `block (2 levels) in define'
/gnu/store/r9icr5yga7r47jdpvzrj5lbmqsw5s9b8-ruby-2.4.3/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/file_utils_ext.rb:58:in `verbose'
/gnu/store/r9icr5yga7r47jdpvzrj5lbmqsw5s9b8-ruby-2.4.3/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/testtask.rb:109:in `block in define'
/gnu/store/r9icr5yga7r47jdpvzrj5lbmqsw5s9b8-ruby-2.4.3/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/gnu/store/r9icr5yga7r47jdpvzrj5lbmqsw5s9b8-ruby-2.4.3/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/gnu/store/r9icr5yga7r47jdpvzrj5lbmqsw5s9b8-ruby-2.4.3/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/gnu/store/r9icr5yga7r47jdpvzrj5lbmqsw5s9b8-ruby-2.4.3/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/gnu/store/r9icr5yga7r47jdpvzrj5lbmqsw5s9b8-ruby-2.4.3/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/gnu/store/r9icr5yga7r47jdpvzrj5lbmqsw5s9b8-ruby-2.4.3/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/gnu/store/r9icr5yga7r47jdpvzrj5lbmqsw5s9b8-ruby-2.4.3/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/gnu/store/r9icr5yga7r47jdpvzrj5lbmqsw5s9b8-ruby-2.4.3/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/gnu/store/r9icr5yga7r47jdpvzrj5lbmqsw5s9b8-ruby-2.4.3/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/gnu/store/r9icr5yga7r47jdpvzrj5lbmqsw5s9b8-ruby-2.4.3/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/gnu/store/r9icr5yga7r47jdpvzrj5lbmqsw5s9b8-ruby-2.4.3/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/gnu/store/r9icr5yga7r47jdpvzrj5lbmqsw5s9b8-ruby-2.4.3/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/gnu/store/r9icr5yga7r47jdpvzrj5lbmqsw5s9b8-ruby-2.4.3/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/gnu/store/r9icr5yga7r47jdpvzrj5lbmqsw5s9b8-ruby-2.4.3/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/gnu/store/r9icr5yga7r47jdpvzrj5lbmqsw5s9b8-ruby-2.4.3/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/gnu/store/r9icr5yga7r47jdpvzrj5lbmqsw5s9b8-ruby-2.4.3/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/gnu/store/r9icr5yga7r47jdpvzrj5lbmqsw5s9b8-ruby-2.4.3/lib/ruby/gems/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/gnu/store/r9icr5yga7r47jdpvzrj5lbmqsw5s9b8-ruby-2.4.3/bin/rake:23:in `load'
/gnu/store/r9icr5yga7r47jdpvzrj5lbmqsw5s9b8-ruby-2.4.3/bin/rake:23:in `<main>'
Tasks: TOP => test
```

**Comment by lucaskanashiro** [comment]
Hi @marcandre,

In Debian we are facing the same issue: https://ci.debian.net/data/autopkgtest/unstable/amd64/r/ruby-backports/1896600/log.gz

I tried to reproduce this failure using a development environment (following README). The `bundle exec rake test` works when you're using the configuration available in your `Gemfile` in master. If you update `activesupport` (Debian will have `rails` version 5 in the next release)  in your `Gemfile` like this:

```
gem 'activesupport', '~>5.2.0' 
# minitest need to be updated to support this version of activesupport
gem 'minitest', '< 5.2.0', :require => false
```

the `bundle exec rake test` fails exactly the way that was reported. Are you sure that `backports` supports `activesupport >= 5`?

**Comment by marcandre** [comment]
Ah, looks like `alias_method_chain` was actually removed altogether in Rails 5. So the test is rightfully complaining that including `backports/rails` (deprecated) after `activesupport` introduces new method. I've simply removed the test on `master`. In the meantime, you can safely ignore it...
