### ISSUE TITLE
Error requiring matrix stdlib

### ISSUE THREAD

**Issue by pmk1c** [marcandre/backports#141]
# Versions

Ruby: 2.7.0
Backports: 3.16.0

# Problem

When requiring the Ruby stdlib `matrix` under Ruby 2.7, with backports enabled, I get the following error. Doing the same without requiring `backports` first, works as intended.

```
irb(main):001:0> require 'backports/latest'
=> true
irb(main):002:0> require 'matrix'
Traceback (most recent call last):
       16: from /home/ruben-zweitag/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
       15: from /home/ruben-zweitag/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
       14: from /home/ruben-zweitag/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
       13: from /home/ruben-zweitag/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
       12: from /home/ruben-zweitag/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
       11: from /home/ruben-zweitag/.asdf/installs/ruby/2.7.0/bin/irb:23:in `<top (required)>'
       10: from /home/ruben-zweitag/.asdf/installs/ruby/2.7.0/bin/irb:23:in `load'
        9: from /home/ruben-zweitag/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/irb-1.2.1/exe/irb:11:in `<top (required)>'
        8: from (irb):2
        7: from /home/ruben-zweitag/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/backports-3.16.0/lib/backports/std_lib.rb:17:in `require_with_backports'
        6: from /home/ruben-zweitag/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/backports-3.16.0/lib/backports/std_lib.rb:17:in `each'
        5: from /home/ruben-zweitag/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/backports-3.16.0/lib/backports/std_lib.rb:18:in `block in require_with_backports'
        4: from /home/ruben-zweitag/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/backports-3.16.0/lib/backports/std_lib.rb:18:in `require'
        3: from /home/ruben-zweitag/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/backports-3.16.0/lib/backports/1.9.2/stdlib/matrix.rb:14:in `<top (required)>'
        2: from /home/ruben-zweitag/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/backports-3.16.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        1: from /home/ruben-zweitag/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/backports-3.16.0/lib/backports/std_lib.rb:9:in `require'
LoadError (cannot load such file -- e2mmap.rb)
```

# Steps to reproduce

1. Run `bundle init` in an empty directory.
2. Add `gem 'backports'` to `Gemfile`
3. Run `bundle install`
4. Run `bundle exec irb`
5. Execute `require 'backports/latest'`
6. Execute `require 'matrix'`

**Comment by marcandre** [comment]
Mmm, right.

There is no longer any good reason to use `backports` for stdlibs as they are being gemified (matrix included). So best is to simply `gem install matrix`...

**Comment by marcandre** [comment]
I fixed it in the latest release to no longer crash.

I also issued a warning that requiring anything else than specific backports is deprecated.

**Comment by marcandre** [comment]
Thanks for reporting the issue.

I had forgotten that requiring `backports/<version of ruby>` was also loading the stdlib...

This is now officially deprecated too. Let me know if you had a special use case.

**Comment by pmk1c** [comment]
No I didn't have a special use case. Just noticed this error while using Middleman, which required all backports (they don't do that anymore). Good to have another deprecation message in the code now. Thanks!
