### ISSUE TITLE
Integer.try_convert breaks fpm

### ISSUE THREAD

**Issue by gintrator** [marcandre/backports#174]
And potentially other programs. When I start `fpm` with, I get the following error.

```
[root@bf921461bfdc project]# fpm
Traceback (most recent call last):
        24: from /usr/local/bin/fpm:23:in `<main>'
        23: from /usr/local/bin/fpm:23:in `load'
        22: from /usr/local/share/gems/gems/fpm-1.13.1/bin/fpm:4:in `<top (required)>'
        21: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
        20: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
        19: from /usr/local/share/gems/gems/fpm-1.13.1/lib/fpm.rb:3:in `<top (required)>'
        18: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
        17: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
        16: from /usr/local/share/gems/gems/fpm-1.13.1/lib/fpm/package.rb:7:in `<top (required)>'
        15: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
        14: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
        13: from /usr/local/share/gems/gems/backports-3.22.0/lib/backports/latest.rb:4:in `<top (required)>'
        12: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
        11: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
        10: from /usr/local/share/gems/gems/backports-3.22.0/lib/backports/3.1.0.rb:3:in `<top (required)>'
         9: from /usr/local/share/gems/gems/backports-3.22.0/lib/backports/tools/require_relative_dir.rb:9:in `require_relative_dir'
         8: from /usr/local/share/gems/gems/backports-3.22.0/lib/backports/tools/require_relative_dir.rb:9:in `each'
         7: from /usr/local/share/gems/gems/backports-3.22.0/lib/backports/tools/require_relative_dir.rb:12:in `block in require_relative_dir'
         6: from /usr/local/share/gems/gems/backports-3.22.0/lib/backports/tools/require_relative_dir.rb:12:in `require_relative'
         5: from /usr/local/share/gems/gems/backports-3.22.0/lib/backports/3.1.0/integer.rb:3:in `<top (required)>'
         4: from /usr/local/share/gems/gems/backports-3.22.0/lib/backports/tools/require_relative_dir.rb:9:in `require_relative_dir'
         3: from /usr/local/share/gems/gems/backports-3.22.0/lib/backports/tools/require_relative_dir.rb:9:in `each'
         2: from /usr/local/share/gems/gems/backports-3.22.0/lib/backports/tools/require_relative_dir.rb:12:in `block in require_relative_dir'
         1: from /usr/local/share/gems/gems/backports-3.22.0/lib/backports/tools/require_relative_dir.rb:12:in `require_relative'
/usr/local/share/gems/gems/backports-3.22.0/lib/backports/3.1.0/integer/try_convert.rb:1:in `<top (required)>': Integer is not a module (TypeError)
```

This is on a fresh `centos:8` image and seems to be specific to `backports-3.22`. Looks like this was *very* recently added, which might explain why Googling didn't get me anywhere: https://github.com/marcandre/backports/commit/88c3119aeff198c43bccdec45fea718e2ade9ee9

Reproducible by pulling the `centos:8` docker image and starting a new instance with the following commands.

```
yum group install "Development Tools"
yum install -y ruby ruby-devel
gem install fpm
fpm
```

**Comment by gintrator** [comment]
Confirmed that this works with `backports-3.21.0`.

```
[root@bf921461bfdc project]# gem uninstall backports

You have requested to uninstall the gem:
        backports-3.22.0

fpm-1.14.1 depends on backports (>= 2.6.2)
If you remove this gem, these dependencies will not be met.
Continue with Uninstall? [yN]  y
Successfully uninstalled backports-3.22.0
[root@bf921461bfdc project]# gem install backports -v 3.21.0
Fetching: backports-3.21.0.gem (100%)
Successfully installed backports-3.21.0
1 gem installed
[root@bf921461bfdc project]# fpm --version
1.14.1
```

**Comment by marcandre** [comment]
Thank you for the very complete bug report, and sorry for the issue.

Should be fixed by 3.22.1

**Comment by gintrator** [comment]
Amazing, thanks for the quick fix!! Can confirm it's working on my end with `3.22.1`.

**Comment by marcandre** [comment]
You're very welcome and thanks for the confirmation
